[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "egc"
version = "0.2.0"
description = "ElectionGuard + Cardano off-chain code"
requires-python = ">=3.9"
dependencies = [
    "pycardano>=0.9.0",
    "aioipfs",
    "cbor2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-asyncio",
    "pytest-mock",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["egc*"]

[tool.pytest.ini_options]

# Run tests in non-alphabetical order.
# I also run tests marked local before the ones marked testnet,
# but that's controlled via test.sh
testpaths = [
  "tests/setup",
  "tests/unit",
  "tests/integration",
  "tests/demo"
]

markers = [
  "local: marks tests as local (not requiring testnet) tests",
  "testnet: marks tests as (slow) testnet tests",
]

# Keep the printed output clean but don't hide errors
log_cli = false
log_cli_level = "INFO"

# Write all logs to a file.
# See also tests/conftest.py for per-component log level tweaks.
log_file = "pytest.log"
log_file_level = "DEBUG"
log_format = "%(asctime)s [%(levelname)s] %(name)s (%(filename)s:%(lineno)d): %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"

pythonpath = ["tests"]
