classes: {
  tx: {
    shape: oval
    style: {
      stroke: black
    }
  }
  datum: {
    shape: rectangle
    style: {
      stroke: black
    }
  }
  channel: {
    style: {
      stroke: transparent
      fill: transparent
    }
  }
}
