classes: {
  tx: {
    shape: oval
    style: {
      stroke: black
    }
  }
  datum: {
    shape: rectangle
    style: {
      stroke: black
    }
  }
  channel: {
    style: {
      stroke: transparent
      fill: transparent
    }
  }
  omitted: {
    label: "..."
    shape: none
    style: {
      # font-size: 50
      shadow: false
      fill: transparent
      stroke: transparent
      shadow: false
      font-size: 28
    }
  }
}
