...@classes

*.class: channel
*.s*.class: datum
*.tx*.class: tx
*.o*.class: omitted

classes: {
  admin: {
    style.stroke: "#e4881b"
  }
}

guardian*.s*.style.fill: "#cdecfb"
guardian*.tx*.style.fill: "#8cd7fa"

guardian1: {
  (* -> *)[*].style.stroke: blue
  s0 -> tx0 -> o -> tx5 -> s5
  o.class: omitted
}

admin.tx1 -> guardian1.s0: {class: admin}
guardian1.s5 -> admin.tx8: {class: admin}

guardian2: {
  (* -> *)[*].style.stroke: blue
  s0 -> tx0 -> o -> tx5 -> s5
}

admin.tx1 -> guardian2.s0: {class: admin}
guardian2.s5 -> admin.tx8: {class: admin}

guardian3: {
  (* -> *)[*].style.stroke: blue
  s0 -> tx0 -> o -> tx5 -> s5
}

admin.tx1 -> guardian3.s0: {class: admin}
guardian3.s5 -> admin.tx8: {class: admin}

admin: {
  (* -> *)[*]: {class: admin}
  s*.style.fill: "#f7d76a"
  tx*.style.fill: "#f7ba6a"
  tx0 -> s0 -> tx1 -> s1 -> tx2 -> o -> tx7 -> s7 -> tx8 -> s8 -> tx9
}

device1: {
  (* -> *)[*].style.stroke: purple
  s*.style.fill: "#cea5e4"
  tx*.style.fill: "#c686ea"
  s0 -> tx0 -> o -> tx8 -> s8
}

admin.tx1 -> device1.s0: {class: admin}
device1.s8 -> admin.tx8: {class: admin}

verifier1: {
  (* -> *)[*].style.stroke: forestgreen
  s*.style.fill: "#b0ce46"
  tx*.style.fill: "#66ba46"
  s0 -> tx0 -> s1
}

admin.tx1 -> verifier1.s0: {class: admin}
verifier1.s1 -> admin.tx8: {class: admin}
