name = "jefdaj/electionguard-cardano"
version = "0.5.1"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'jefdaj/electionguard-cardano'"

[repository]
user = "jefdaj"
project = "electionguard-cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[config.default]
stt_prefix = "election"
