# based on https://github.com/IntersectMBO/cardano-node/blob/master/docker-compose.yml
# only change so far is to put volumes under ./data/

services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:${CARDANO_NODE_VERSION:-latest}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - ./data/node-db:/data/db
      - ./data/node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  cardano-submit-api:
    image: ghcr.io/intersectmbo/cardano-submit-api:${CARDANO_SUBMIT_API_VERSION:-latest}
    environment:
      - NETWORK=${NETWORK:-mainnet}
    depends_on:
      - cardano-node
    volumes:
      - ./data/node-ipc:/node-ipc
    ports:
      - 8090:8090
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
