services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:11.0.1
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:
      - ../cardano-node-ogmios/config/network/${NETWORK:-preview}/cardano-node:/config
      - ../cardano-node-ogmios/data/node-db:/data
      - ../cardano-node-ogmios/data/node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    networks:
      - shared-net

  ogmios:
    # TODO does ktorz normally publish "latest" from the dev branch?
    # image: cardanosolutions/ogmios:v6.14.0
    image: 3a21f883f83e # custom version i built for now
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json"
    ]
    volumes:
      # TODO make the same as the node one above?
      - ../cardano-node-ogmios/config/network/${NETWORK:-preview}:/config
      - ../cardano-node-ogmios/data/node-ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337
    networks:
      - shared-net # TODO remove?

  # In this test there's just one IPFS container.
  # I've tested already that a more realistic setup with a bunch of them also works.
  ipfs:
    image: ipfs/kubo:v0.34.1 # TODO upgrade to current version
    volumes:
      - ./data/ipfs:/data/ipfs
    ports:
      - 4001:4001 # ipfs swarm
      - 5001:5001 # ipfs api (and webui on /webui)
    networks:
      - shared-net # TODO remove?

  # This is number 2 to distinguish it from verifier1 on the publish side.
  # That doesn't have a docker container.
  verifier2:
    image: ghcr.io/jefdaj/electionguard-python:1.4.0
    command: [
      "sh", "-c", "while true; do sleep 1000; done"
    ]
    volumes:
      - ./egpy_scripts:/scripts
      - ./data/verifier2:/data/private

# allow communication with other docker-compose networks, for example kupo
# TODO would just using the ipc socket work across networks instead?
networks:
  shared-net:
    driver: bridge
