[project]
name = "egc-client-server-sketch"
version = "0.1.0"
description = "ElectionGuard+Cardano Client/Server Sketch"
authors = [{ name = "jefdaj", email = "1198065+jefdaj@users.noreply.github.com" }]
requires-python = ">=3.13,<3.14"
readme = "README.md"
license = "MIT"
maintainers = []
keywords = []
classifiers = [
]
dependencies = [
    "quart>=0.20.0",
    "pycardano>=0.9.0",
    "aioipfs",
    "cbor2==5.8.0",
    "cbor2pure==5.8.0",
    "deepdiff>=9.1.0",
]

[project.scripts]
egc        = "egc_client.client:main"
egc-server = "egc_server.server:main"

[dependency-groups]
dev = [
]

[tool.hatch.build.targets.sdist]
include = [
    "src/egc",
    "src/egc_client",
    "src/egc_server",
]

[tool.hatch.build.targets.wheel]
include = [
    "src/egc",
    "src/egc_client",
    "src/egc_server",
]

[tool.hatch.build.targets.wheel.sources]
"src/egc"        = "egc"
"src/egc_client" = "egc_client"
"src/egc_server" = "egc_server"

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"
