// Second integration test: simplest happy path through the lifecycle of a subchannel.
// Builds on the admin channel tests in validators/tests/integration/minimal.tests.ak.

// TODO add one subchannel during onboarding phase, and also advance?
// TODO rm the one subchannel
// TODO end election as before, maybe with a slightly larger seq

test happy_subchannel_add1() { True }
test happy_subchannel_rm1() { True }
