services:
  kupo:
    image: cardanosolutions/kupo:latest # TODO pin to working hash
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - 127.0.0.1:1442:1442
    command: [
      "--node-socket", "/node-ipc/node.socket",
      "--node-config", "/node-config/config.json",
      "--since", "${KUPO_SINCE_PREVIEW:-origin}",
      "--match", "${KUPO_MATCH_PREVIEW:-*}",
      "--workdir", "/db",
      "--host", "0.0.0.0",
      "--port", "1442"
    ]
    volumes:
      - ../cardano-node-ogmios/config/network/preview/cardano-node:/node-config
      - ../cardano-node-ogmios/data/node-ipc:/node-ipc
      - ./data/kupo-db:/db
    networks:
      - cardano-node-ogmios_shared-net
    # TODO put back if/when you add mainnet
    # profiles: ["preview"]

# network with the node docker-compose
networks:
  cardano-node-ogmios_shared-net:
    external: true
