[project]
name = "electionguard-cardano"
version = "0.3.0"
description = "End-to-end verifiable blockchain elections."
authors = [{ name = "jefdaj", email = "1198065+jefdaj@users.noreply.github.com" }]
requires-python = ">=3.13,<3.14"
readme = "README.md"
license = "MIT"
maintainers = []
keywords = []
classifiers = [
]
dependencies = [
    "pycardano>=0.9.0",
    "aioipfs",
    "cbor2==5.8.0",
    "cbor2pure==5.8.0",
    "deepdiff>=9.1.0",
    "httpx>=0.28.1",
    "click>=8.4.2",
    "fastapi>=0.139.0",
    "uvicorn>=0.51.0",
    "jinja2>=3.1.6",
    "qrcode[pil]>=8.2",
    "opencv-python-headless>=5.0.0.93",
    "cloup>=3.1.0",
    "electionguard==1.4.0",
    "pynacl>=1.6.2",
]

[tool.uv.sources]
electionguard = { git = "https://github.com/jefdaj/electionguard-python", branch = "nix-lib-outputs" }

[project.scripts]
egc = "egc_app.cli:cli"

[dependency-groups]
dev = [
    "pytest>=7.0",
    "pytest-asyncio",
    "pytest-mock",
]

[tool.hatch.build.targets.sdist]
include = [
    "src/egc",
    "src/egc_app",
]

[tool.hatch.build.targets.wheel]
include = [
    "src/egc",
    "src/egc_app",
]

[tool.hatch.build.targets.wheel.sources]
"src/egc"     = "egc"
"src/egc_app" = "egc_app"

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]

pythonpath = ["tests"]

# Run tests in a particular non-alphabetical order.
# I also run tests marked local before the ones marked testnet,
# but that's controlled via CLI args in test.sh
testpaths = [
  "tests/setup",
  "tests/unit",
  "tests/integration",
  "tests/demo"
]

markers = [
  "local: marks tests as local (not requiring testnet) tests",
  "testnet: marks tests as (slow) testnet tests",
]

# Keep the printed output clean but don't hide errors
log_cli = false
log_cli_level = "INFO"

# Write all logs to a file.
# See also tests/conftest.py for per-component log level tweaks.
log_file = "pytest.log"
log_file_level = "DEBUG"
log_format = "%(asctime)s [%(levelname)s] %(name)s (%(filename)s:%(lineno)d): %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
