{
    "networks": {
        "default": {
            "name": "verifier"
        }
    },
    "services": {
        "verifier1": {
            "command": [
                "sh",
                "-c",
                "while true; do sleep 1000; done\n"
            ],
            "environment": {},
            "image": "ghcr.io/jefdaj/electionguard-python:1.4.0",
            "sysctls": {},
            "volumes": [
                "./scripts:/scripts/",
                "/home/jefdaj/myrepos/electionguard-cardano/milestone1/local-election/data/public:/data/public",
                "./data/private/verifier_1:/data/private"
            ]
        }
    },
    "version": "3.4",
    "volumes": {},
    "x-arion": {
        "images": [],
        "project": {
            "name": "verifier"
        },
        "serviceInfo": {
            "verifier1": {
                "defaultExec": [
                    "/bin/sh"
                ]
            }
        }
    }
}

