name = "jefdaj/electionguard-cardano"
version = "0.0.2"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'jefdaj/electionguard-cardano'"

[repository]
user = "jefdaj"
project = "electionguard-cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "3.0.0"
source = "github"

[config.default.stt_name]
encoding = "utf-8"
bytes = "electionguard-cardano-channel-stt"
